### ISSUE TITLE
extra `does nothing` expression in header matches?

### ISSUE THREAD

**Issue by msftrncs** [Microsoft/vscode-markdown-tm-grammar#30]
In the expressions for the headers,
```regex
(#{1})\s*(?=[\S[^#]])(.*?)\s*(\s+#+)?$\n?
```

What does the lookahead `(?=[\S[^#]])` accomplish?  Would seem its trying to say, look ahead for a non-white space that's also not a '#'.

Looks like it was supposed to stop the match if the count of '#'s is greater than 6, or if there is not a space after the set of '#'s.   VS Code's syntax highlighting for markdown and the markdown previewer are not seeming to match up here either.

```markdown
#header
```

This highlights as a header, but doesn't preview as such.

```markdown
####### Header
```

This also highlights as a header, but doesn't preview as such.

GITHUB seems to agree:
#header (not a header)
# header

**Comment by mjbvz** [comment]
I'm not really sure. I think the specific line was inherited from the original textmate grammar we forked. 

We generally try to match the behavior of commonmark (which requires a space after the `#`) but make exceptions in some cases. Since many markdown flavors do not require the space after the `#`, we decided to relax this one restriction. However our in-editor markdown preview still does target common mark so you need the space after the `#`
