### ISSUE TITLE
Adding attributes to fenced markdown code blocks breaks syntax highlighting

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode-markdown-tm-grammar#62]
The following highlights fine in VS Code markdown.
````
```py
def greetings():
    print("Hello world!")
```
````
If I add an attribute such line highlighting or a title, syntax highlighting is gone.
````
```py{1}:title=greet.py
def greetings():
    print("Hello world!")
```
````
How about just discarding everything after the first special character when reading the fence's language specifier?

**Comment by mjbvz** [comment]
What markdown engine uses that syntax?

**Comment by janosh** [comment]
@mjbvz Not part of an engine. It's preprocessing but the practice of adding various attributes to code fences is quite wide spread. In my case, the titles are powered by [`gatsby-remark-code-titles`](https://www.gatsbyjs.org/packages/gatsby-remark-code-titles) and the line lighlighting by [`gatsby-remark-vscode`](https://www.gatsbyjs.org/packages/gatsby-remark-vscode)

**Comment by mjbvz** [comment]
Ok, I asked because we do already ignore attribute but other parsers require a space between the language name and attributes

PRs welcome but keep in mind that some language names do contain special characters (`c++`, `c#`, ...). You likely need to change this line and add tests: https://github.com/microsoft/vscode-markdown-tm-grammar/blob/b6d7f715d32c774aca4fc6a9dd19103090c41cfa/build.js#L83
